version: '3'
services:
  api:
    image: gobarber:1.0.2
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    command: yarn dev
    depends_on:
      - db
    networks:
      - apidb

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123
    volumes:
      - ../gobarber-data/pgdata/:/var/lib/postgresql/data/
    networks:
      - apidb

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - ../gobarber-data/mongo/:/data/db
    ports:
      - 27017:27017
    networks:
      - apidb

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: andersonhsantanappa@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
      POSTGRES_DB: gobarber
    ports:
      - 5050:80
    depends_on:
      - db
    volumes:
      - ../gobarber-data/pgadmin:/var/lib/pgadmin/
    networks:
      - apidb

networks:
  apidb:

volumes:
  postgres:
  pgadmin:
